INADEF/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth.views import LoginView, logout
from main.views import Home
from indicadores import urls as indicadoresUrl
from indicadores.views import Dashboard
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', logout, name="logout"),
    path('dashboard/', Dashboard.as_view(), name="dashboard"),
    path('indicadores/', include(indicadoresUrl, namespace="indicadores")),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
            ),

]

indicadores/urls.py
from django.urls import path
from .views import indicadoresListView, indicadoresDetailView, SatisfactorioList, RegularList, PesimoList, ResumenAreaDetail, ResumenAreaList, ResumenGeneral
app_name="indicadores"

urlpatterns = [
    path('', indicadoresListView.as_view(), name="list"),
    path('satisfactorio/', SatisfactorioList.as_view(), name="satisfactorio"),
    path('regular/', RegularList.as_view(), name="regular"),
    path('pesimo/', PesimoList.as_view(), name="pesimo"),
    path('<int:pk>/', indicadoresDetailView.as_view(), name="detail"),
    path('resumen/seleccionar_area/', ResumenAreaList.as_view(), name="resumen_area_list" ),
    path('resumen/general/', ResumenGeneral.as_view(), name="resumen_general"),
    path('resumen/<str:username>/', ResumenAreaDetail.as_view(), name="resumen_area_detail"),
    #path('<int:pk>/evidencias/<int:epk>/', EvidenciasDetailView.as_view(), name="evidencia_det"),

]

indicadores/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

choices_nivel = (
        ('Gestión', 'Gestión'),
        ('Desempeño', 'Desempeño'),
    )

choices_status = (
    ('Satisfactorio', 'Satisfactorio'),
    ('Regular', 'Regular'),
    ('Insatisfactorio', 'Insatisfactorio'),
    ('NCS','NCS')
)


class Indicador(models.Model):

    indicador = models.CharField(max_length=10)
    nombre = models.TextField()
    descripcion = models.TextField(blank=True, null=True)
    metodo_calculo = models.TextField(blank=True, null=True)
    nivel = models.CharField(max_length=15, choices=choices_nivel, blank=True, null=True)
    dimension = models.CharField(max_length=144, blank=True, null=True)
    criterios_evaluacion = models.TextField(blank=True, null=True)
    area = models.ForeignKey(User, related_name='indicadores', on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=choices_status)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    evidencia = models.FileField(upload_to="evidencias/archivos/", blank=True, null=True)

    def __str__(self):
        return self.indicador + ' - ' + self.nombre

    def get_absolute_url(self):
        return reverse('indicadores:detail', kwargs={'pk':self.pk})


class Evidencia(models.Model):

    indicador = models.ForeignKey(Indicador, related_name="evidencias", on_delete=models.CASCADE)
    titulo = models.TextField()
    porcentaje_total = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    porcentaje_real = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    archivo = models.FileField(upload_to='evidencias/', blank=True, null=True)
    completada = models.BooleanField(default=False)

    def __str__(self):
        return self.indicador.indicador + ' - ' + self.titulo

    def get_absolute_url(self):
        return reverse('indicadores:evidencia_det', kwargs={'pk':self.indicador.id, 'epk':self.pk})


class Subevidencia(models.Model):

    evidencia = models.ForeignKey(Evidencia, related_name="subevidencias", on_delete=models.CASCADE)
    titulo = models.TextField()
    porcentaje = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    archivo = models.FileField(upload_to='evidencias/', blank=True, null=True)
    completada = models.BooleanField(default=False)

    def __str__(self):
        return self.evidencia.indicador.indicador + ' - ' + self.evidencia.titulo + ' - ' + self.titulo


class Seguimiento(models.Model):

    indicador = models.ForeignKey(Indicador, related_name="seguimientos", on_delete=models.CASCADE)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.indicador.indicador + ' - ' + self.cuerpo

    class Meta:
        ordering = (('-fecha'),)

indicadores/forms.py
from django import forms
from .models import Indicador


class UploadFileForm(forms.ModelForm):
    evidencia = forms.FileField(label="")
    class Meta:
        model = Indicador
        fields = ['evidencia']

indicadores/views.py
from django.shortcuts import render, redirect
from django import views
from .models import Indicador, Evidencia
from django.db.models import Q
from .forms import UploadFileForm
from django.contrib.auth.models import User

class Dashboard(views.View):

    def get(self, request):
        template_name="indicadores/dashboard.html"

        if request.user.is_superuser:
            total = len(Indicador.objects.all())
            verde = len(Indicador.objects.filter(status="Satisfactorio"))
            amarillo = len(Indicador.objects.filter(status="Regular"))
            rojo = len(Indicador.objects.filter(status="Insatisfactorio"))
        else:
            total = len(Indicador.objects.filter(area=request.user))
            verde = len(Indicador.objects.filter(area=request.user, status="Satisfactorio"))
            amarillo = len(Indicador.objects.filter(area=request.user, status="Regular"))
            rojo = len(Indicador.objects.filter(area=request.user, status="Insatisfactorio"))
        print(total)

        context = {'total':total,
                   'verde':verde,
                   'amarillo':amarillo,
                   'rojo':rojo}

        return render(request, template_name, context)


class indicadoresListView(views.View):

    def get(self, request):
        print("LLEGO A TODOS")
        template_name="indicadores/indicador_list.html"

        q = request.GET.get('q')
        print(q)
        indicadores = Indicador.objects.filter(area=request.user)

        if q:
            indicadores = Indicador.objects.filter(Q(area=request.user),
                                                    Q(nombre__icontains=q)|
                                                    Q(indicador__icontains=q)|
                                                     Q(descripcion__icontains=q)).distinct()

        total = len(Indicador.objects.filter(area=request.user))
        verde = len(Indicador.objects.filter(area=request.user, status="Satisfactorio"))
        amarillo = len(Indicador.objects.filter(area=request.user, status="Regular"))
        rojo = len(Indicador.objects.filter(area=request.user, status="Insatisfactorio"))

        context = {'indicadores':indicadores,
                   'tab': 'all',
                   'total': total,
                   'verde': verde,
                   'amarillo': amarillo,
                   'rojo': rojo
                   }

        return render(request, template_name, context)

class SatisfactorioList(views.View):

    def get(self, request):
        print("LLEGO A VERDE")
        template_name = "indicadores/indicador_list.html"

        q = request.GET.get('q')
        indicadores = Indicador.objects.filter(area=request.user, status="Satisfactorio")

        if q:
            indicadores = Indicador.objects.filter(Q(area=request.user),
                                                   Q(status="Satisfactorio"),
                                                   Q(nombre__icontains=q) |
                                                   Q(indicador__icontains=q) |
                                                   Q(descripcion__icontains=q)).distinct()


        total = len(Indicador.objects.filter(area=request.user))
        verde = len(Indicador.objects.filter(area=request.user, status="Satisfactorio"))
        amarillo = len(Indicador.objects.filter(area=request.user, status="Regular"))
        rojo = len(Indicador.objects.filter(area=request.user, status="Insatisfactorio"))

        context = {'indicadores': indicadores,
                   'tab': 'green',
                   'total': total,
                   'verde': verde,
                   'amarillo': amarillo,
                   'rojo': rojo
                   }

        return render(request, template_name, context)


class RegularList(views.View):

    def get(self, request):
        print("LLEGO A AMARILLO")
        template_name = "indicadores/indicador_list.html"
        q = request.GET.get('q')
        indicadores = Indicador.objects.filter(area=request.user, status="Regular")
        print(q)
        if q:
            indicadores = Indicador.objects.filter(Q(area=request.user),
                                                   Q(status="Regular"),
                                                   Q(nombre__icontains=q) |
                                                   Q(indicador__icontains=q) |
                                                   Q(descripcion__icontains=q)).distinct()

        print(indicadores)
        total = len(Indicador.objects.filter(area=request.user))
        verde = len(Indicador.objects.filter(area=request.user, status="Satisfactorio"))
        amarillo = len(Indicador.objects.filter(area=request.user, status="Regular"))
        rojo = len(Indicador.objects.filter(area=request.user, status="Insatisfactorio"))

        context = {'indicadores': indicadores,
                   'tab': 'yellow',
                   'total': total,
                   'verde': verde,
                   'amarillo': amarillo,
                   'rojo': rojo
                   }

        return render(request, template_name, context)

class PesimoList(views.View):

    def get(self, request):

        print("LLEGO A ROJO")
        template_name = "indicadores/indicador_list.html"
        q = request.GET.get('q')
        indicadores = Indicador.objects.filter(area=request.user, status="Insatisfactorio")

        if q:
            indicadores = Indicador.objects.filter(Q(area=request.user),
                                                   Q(status="Insatisfactorio"),
                                                   Q(nombre__icontains=q) |
                                                   Q(indicador__icontains=q) |
                                                   Q(descripcion__icontains=q)).distinct()


        total = len(Indicador.objects.filter(area=request.user))
        verde = len(Indicador.objects.filter(area=request.user, status="Satisfactorio"))
        amarillo = len(Indicador.objects.filter(area=request.user, status="Regular"))
        rojo = len(Indicador.objects.filter(area=request.user, status="Insatisfactorio"))

        context = {'indicadores': indicadores,
                   'tab': 'red',
                   'total': total,
                   'verde': verde,
                   'amarillo': amarillo,
                   'rojo': rojo
                   }

        return render(request, template_name, context)



class indicadoresDetailView(views.View):

    def get(self, request, pk):

        template_name="indicadores/indicador_detail.html"
        indicador = Indicador.objects.get(pk=pk)
        form = UploadFileForm()
        context = {'indicador':indicador, 'form':form}

        return render(request, template_name, context)

    def post(self, request, pk):

        indicador = Indicador.objects.get(pk=pk)
        form = UploadFileForm(request.POST, request.FILES, instance=indicador)
        print(form)
        if form.is_valid():
            print("Valido")
            form_data = form.save(commit=False)
            print(form_data)
            form_data.save()
            return redirect('indicadores:detail', pk)
        else:
            return redirect('indicadores:list')



class EvidenciasDetailView(views.View):

    def get(self, request, pk, epk):

        template_name="indicadores/evidencia_detail.html"
        indicador = Indicador.objects.get(pk=pk)
        evidencia = Evidencia.objects.get(pk=epk, indicador=indicador)

        context = {'evidencia': evidencia}

        return render(request, template_name, context)


class ResumenAreaList(views.View):

    def get(self, request):

        template_name="indicadores/resumen/lista.html"
        q = request.GET.get('q')

        areas = User.objects.all()

        if q:
            areas = User.objects.filter(Q(username__icontains=q)|
                                        Q(first_name__icontains=q)|
                                        Q(last_name__icontains=q))

        context = {'areas': areas}

        return render(request, template_name, context)


class ResumenAreaDetail(views.View):

    def get(self, request, username):

        template_name="indicadores/resumen/detalle.html"
        area = User.objects.get(username=username)
        indicadores = Indicador.objects.filter(area=area).order_by('indicador')
        verde = len(Indicador.objects.filter(area=area, status="Satisfactorio"))
        amarillo = len(Indicador.objects.filter(area=area, status="Regular"))
        rojo = len(Indicador.objects.filter(area=area, status="Insatisfactorio"))

        context = {'indicadores':indicadores, "area": area, "verde": verde, "amarillo": amarillo, "rojo":rojo}

        return render(request, template_name, context)


class ResumenGeneral(views.View):
    def get(self, request):

        template_name="indicadores/resumen/general.html"
        areas = User.objects.all()
        arrayy = []
        for area in areas:
            dict = {
                "usuario": area.username,
                "nombre": area.get_full_name(),
                "total": Indicador.objects.filter(area=area).count(),
                "verdes": Indicador.objects.filter(area=area, status="Satisfactorio").count(),
                "amarillos": Indicador.objects.filter(area=area, status="Regular").count(),
                "rojos": Indicador.objects.filter(area=area, status="Insatisfactorio").count(),
                "ncs": Indicador.objects.filter(area=area, status="NCS").count(),
            }
            arrayy.append(dict)

        total = len(Indicador.objects.all())
        verde = len(Indicador.objects.filter(status="Satisfactorio"))
        amarillo = len(Indicador.objects.filter(status="Regular"))
        rojo = len(Indicador.objects.filter(status="Insatisfactorio"))

        context = {"data": arrayy, "total": total, "verde": verde, "amarillo":amarillo, "rojo": rojo}

        return render(request, template_name, context)

indicadores/templates/indicadores/resumen/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <div class="row">
            <div class="col-md-12 margin-bottom-small">
                <h2 class="text-center">{{area.get_full_name}}</h2>
            </div>
        </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
              <thead class="background-primary color-accent">
                <tr>
                  <th scope="col">Indicador</th>
                  <th scope="col">Nombre</th>
                  <th scope="col">Status</th>
                  <th scope="col">Evidencia</th>
                </tr>
              </thead>
              <tbody>
                {% for indicador in indicadores %}
                    <tr class="{% if indicador.status == 'Satisfactorio' %}
                          green-hover
                          {% elif indicador.status == 'Regular' %}
                           yellow-hover
                            {% elif indicador.status == 'Insatisfactorio' %}
                            red-hover
                            {% endif %}">
                    <th scope="row">{{ indicador.indicador }}</th>
                    <td>{{ indicador.nombre }}</td>
                    <td>{{ indicador.status }}</td>
                    {% if indicador.evidencia %}
                        <td><a href="/media{{ indicador.evidencia }}">Descargar</a></td>
                    {% else %}
                        <td>Aún no presentada</td>
                    {% endif %}
                    </tr>
                {% endfor %}

              </tbody>
            </table>
        </div>
    </div>
    <div class="row cards-dashboards">
            <div class="col-md-3 text-center">
               <div class="card card-indicadores">
                   <div class="card-body d-flex flex-column justify-content-around">
                       <div class="card-title">{{ indicadores.count }} </div>
                       <div class="card-text">Total</div>
                   </div>
               </div>
            </div>

            <div class="col-md-3 text-center">
               <div class="card card-indicadores green-back">
                   <div class="card-body d-flex flex-column justify-content-around">
                       <div class="card-title">{{ verde }} </div>
                       <div class="card-text">Satisfactorios</div>
                   </div>
               </div>
            </div>

            <div class="col-md-3 text-center">
               <div class="card card-indicadores yellow-back">
                   <div class="card-body d-flex flex-column justify-content-around">
                       <div class="card-title">{{ amarillo }} </div>
                       <div class="card-text">Regulares</div>
                   </div>
               </div>
            </div>
             <div class="col-md-3 text-center">
                   <div class="card card-indicadores red-back">
                       <div class="card-body d-flex flex-column justify-content-around">
                           <div class="card-title">{{ rojo }} </div>
                           <div class="card-text">Insatisfactorios</div>
                       </div>
                   </div>
                </div>
    </div>
{% endblock %}

indicadores/templates/indicadores/resumen/general.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
     <div class="row">
            <div class="col-md-12 margin-bottom-small">
                <h2 class="text-center">Resumen general de indicadores</h2>
            </div>
        </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
              <thead class="background-primary color-accent" style="text-align: center">
                <tr>
                  <th scope="col" style="text-align: justify">Área</th>
                    <th scope="col">Total</th>
                  <th scope="col"># Satisfactorios</th>
                  <th scope="col"># Regulares</th>
                  <th scope="col"># Insatisfactorios</th>
                    <th scope="col"># NCS</th>
                </tr>
              </thead>
              <tbody style="text-align: center">
                {% for d in data %}
                    {% if d.total > 0 %}
                        <tr>
                            <th scope="row" style="text-align: justify"><a href="{% url 'indicadores:resumen_area_detail' d.usuario %}">{{ d.nombre }}</a></th>
                            <td>{{ d.total }}</td>
                            <td>{{ d.verdes }}</td>
                            <td>{{ d.amarillos }}</td>
                            <td>{{ d.rojos }}</td>
                            <td>{{ d.ncs }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}

              </tbody>
            </table>
        </div>
    </div>
    <div class="row cards-dashboards">
            <div class="col-md-3 text-center">
               <div class="card card-indicadores">
                   <div class="card-body d-flex flex-column justify-content-around">
                       <div class="card-title">{{ total }} </div>
                       <div class="card-text">Total</div>
                   </div>
               </div>
            </div>

            <div class="col-md-3 text-center">
               <div class="card card-indicadores green-back">
                   <div class="card-body d-flex flex-column justify-content-around">
                       <div class="card-title">{{ verde }} </div>
                       <div class="card-text">Satisfactorios</div>
                   </div>
               </div>
            </div>

            <div class="col-md-3 text-center">
               <div class="card card-indicadores yellow-back">
                   <div class="card-body d-flex flex-column justify-content-around">
                       <div class="card-title">{{ amarillo }} </div>
                       <div class="card-text">Regulares</div>
                   </div>
               </div>
            </div>
             <div class="col-md-3 text-center">
                   <div class="card card-indicadores red-back">
                       <div class="card-body d-flex flex-column justify-content-around">
                           <div class="card-title">{{ rojo }} </div>
                           <div class="card-text">Insatisfactorios</div>
                       </div>
                   </div>
                </div>
    </div>
{% endblock %}

indicadores/templates/indicadores/resumen/lista.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                        <form action="{% url 'indicadores:resumen_area_list' %}"
                    method="get" class="d-flex flex-row">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Buscar" name="q" value="{{ request.GET.q }}" aria-label="Nombre de Usuario" aria-describedby="basic-addon1" >
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">
                                   <input class="btn btn-outline-primary " type="submit" name="submit" value="Go">
                                </span>
                            </div>

                        </div>

                </form>
            </div>
        </div>
    <div class="list-group">
        <div class="row">
                {% for area in areas %}
                    {% if area.indicadores.count > 0 %}
                    <div class="col-md-6">
                        <a href="/indicadores/resumen/{{ area.username }}/" class="list-group-item margin-bottom-small list-group-item-action flex-column aligm-items-start principal-hover">

                            <div class="d-flex justify-content-between">
                                <h5>{{ area.get_full_name }}</h5>
                            </div>
                            <small> No. de evidencias: {{ area.indicadores.count }}</small>
                        </a>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}