INADEF/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth.views import LoginView, logout
from main.views import Home
from indicadores import urls as indicadoresUrl
from indicadores.views import Dashboard
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', logout, name="logout"),
    path('dashboard/', Dashboard.as_view(), name="dashboard"),
    path('indicadores/', include(indicadoresUrl, namespace="indicadores")),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
            ),

]

indicadores/urls.py
from django.urls import path
from .views import indicadoresListView, indicadoresDetailView, SatisfactorioList, RegularList, PesimoList, ResumenAreaDetail, ResumenAreaList, ResumenGeneral
app_name="indicadores"

urlpatterns = [
    path('', indicadoresListView.as_view(), name="list"),
    path('satisfactorio/', SatisfactorioList.as_view(), name="satisfactorio"),
    path('regular/', RegularList.as_view(), name="regular"),
    path('pesimo/', PesimoList.as_view(), name="pesimo"),
    path('<int:pk>/', indicadoresDetailView.as_view(), name="detail"),
    path('resumen/seleccionar_area/', ResumenAreaList.as_view(), name="resumen_area_list" ),
    path('resumen/general/', ResumenGeneral.as_view(), name="resumen_general"),
    path('resumen/<str:username>/', ResumenAreaDetail.as_view(), name="resumen_area_detail"),
    #path('<int:pk>/evidencias/<int:epk>/', EvidenciasDetailView.as_view(), name="evidencia_det"),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="shortcut icon" href="{% static '/images/favicon.ico' %}" type="image/x-icon">
      <link rel="icon" href="{% static '/images/favicon.ico' %}" type="image/x-icon">
    <title>INAFED Indicadores</title>
    <!-- Styles CSS -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/images/favicon.com' %}" type="image/x-icon">
      <link rel="icon" href="{% static '/images/favicon.com' %}" type="image/x-icon">
    <link href="{% static '/open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet">
    <!-- Own Styles -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light background-primary justify-content-around" style="max-height:80px !important;">
    <div class="col-lg-2 text-right">
        <div class="dropdown">
            {% if request.user.is_superuser %}
                <a class="btn dropdown-toggle color-accent" role="button" id="dropdownResumenes" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Resúmenes
                </a>

          <div class="dropdown-menu" aria-labelledby="dropdownResumenes">
              <a class="dropdown-item" href="{% url 'indicadores:resumen_area_list' %}">Por área</a>
              <a class="dropdown-item" href="{% url 'indicadores:resumen_general' %}">General</a>
          </div>
            {% endif %}
        </div>
      </div>
     <div class="col-lg-2 text-right">
        <div class="dropdown">
            {% if request.user.is_authenticated and request.user.indicadores.count > 0 %}
                <a class="btn dropdown-toggle color-accent" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Indicadores
                </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'dashboard' %}">Resumen</a>
              <a class="dropdown-item" href="{% url 'indicadores:list' %}">Todos los indicadores</a>
          </div>
            {% endif %}
        </div>
      </div>
      <div class="col-lg-4 text-center">
          <a href="{% url 'home' %}">
            <img src="{%static 'images/logo.jpg'%}" alt="Gobierno de la gente" class="logo-img">
          </a>
      </div>
      {% if request.user.is_authenticated %}
        <div class="col-md-2 text-left">
          <a class="btn color-accent" href="{% url 'dashboard' %}">{{ request.user.get_full_name }}</a>
        </div>
        <div class="col-md-2 text-left">
          <a class="btn color-accent" href="{% url 'logout' %}">Cerrar sesión</a>
        </div>
      {% else %}
        <div class="col-md-4 text-left">
          <a class="btn color-accent" href="{% url 'login' %}">Iniciar sesión</a>
        </div>
      {% endif %}
      
    </div>
    </nav>
    <!-- End navbar -->
    <div class="container paddings-vertical">
      {% block content %}

      {% endblock content %}
    </div>
  </body>
  <!-- Scripts -->
  <!-- Boostrap JS -->
  <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
  {% block script %}
  {% endblock script %}
  <script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</html>